### ISSUE TITLE
Does the project need the exact dependencies specified in the README?

### ISSUE THREAD

**Issue by runiq** [N-SDM/N-SDM#13]
Hi! I'm an HPC administrator with [a German university](https://www.uni-halle.de/?lang=en). One of our users wants to use this software package and has asked me to install it for them.

Does it really need the exact versions of packages you specify in the README, or can I substitute some of them with other versions? I'm a little hesitant to install an all-new pipeline just for a single application. Our cluster is old enough to predate EasyBuild & friends, so installation is mostly manual for the time being.

**Comment by N-SDM** [comment]
Hi! The versions in the readme are the one used for developing NSDM, inter module compatibility is always a tricky challenge, but other combinations should work. For example we recently implemented it in a new cluster with the following list:
gcc/8.2.0 r/4.2.2
r/4.2.2
proj/5.2.0
perl
curl
geos/3.9.1
gdal

**Comment by runiq** [comment]
Thanks a lot, that's great to hear. :)
