### ISSUE TITLE
files not found in settings/tmp/

### ISSUE THREAD

**Issue by micahwilhelm** [N-SDM/N-SDM#9]
I'm trying to run n-sdm on the Hyperion cluster at the WSL. Unfortunately, v1.0.1 doesn't run out of the box (for me) using the nsdm-project example. There are some files such as n_spe.txt spe_runs.txt which should exist in nsdm-project/settings/tmp/ but the run script cannot find them. Is this a known bug?

nohup bash nsdm.sh > nsdm.out

**nsdm.out shows the following errors:**
> Welcome to this new nsdm-project run 9e9403
> Submitted batch job 9542396
> cat: /home/wilhelm/nsdm//tmp/nsdm-project/settings/tmp/n_spe.txt: No such file or directory
> N-SDM settings defined and species occurence data for  species disaggregated
> cat: /home/wilhelm/nsdm//tmp/nsdm-project/settings/tmp/spe_runs.txt: No such file or directory
> Starting N-SDM run 1 out of  runs
> N-SDM settings updated
> cat: /home/wilhelm/nsdm//tmp/nsdm-project/settings/tmp/n_spe.txt: No such file or directory
> expr: syntax error
> expr: syntax error
> expr: syntax error
> expr: syntax error
> expr: syntax error
> expr: syntax error
> expr: syntax error
> Submitted batch job 9542397
> PRE modelling datasets generated
> sbatch: error: Batch job submission failed: Invalid job array specification
> GLO data preparation and covariate selection done
> sbatch: error: Batch job submission failed: Invalid job array specification
> GLO modelling done
> sbatch: error: Batch job submission failed: Invalid job array specification
> GLO ensembling done
> sbatch: error: Batch job submission failed: Invalid job array specification
> REG data preparation and covariate selection done
> sbatch: error: Batch job submission failed: Invalid job array specification
> REG modelling done
> sbatch: error: Batch job submission failed: Invalid job array specification
> REG ensembling and scale nesting done
> sbatch: error: Batch job submission failed: Invalid job array specification
> individual FUT GLO predictions done
> sbatch: error: Batch job submission failed: Invalid job array specification
> FUT GLO ensembling done
> sbatch: error: Batch job submission failed: Invalid job array specification
> individual FUT REG predictions done
> sbatch: error: Batch job submission failed: Invalid job array specification
> FUT REG ensembling and scale nesting done
> sbatch: error: Batch job submission failed: Invalid job array specification
> Final evaluation done
> Sacct outputs analysis done
> ODMAP protocol generated
> find: 'd2_models/': No such file or directory
> Main outputs sync to saving location
> Finished!

If more information is needed please let me know.

**Comment by N-SDM** [comment]
These files are generated during the preparation step by "./scripts/nsdm-project/main/0_mainPRE/nsdm_update.R", which is run after pre_A.R and pre_B.R. Something wrong might have happen during pre_A or pre_B, could you check the error files in ./scripts/nsdm-project/main/0_mainPRE/ ?

**Comment by micahwilhelm** [comment]
Thanks for the tip! The system was not finding the nsdm R package. All is well now.
